services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak-data-volume: /var/lib/keycloak/data
    ports:
      - "9090:8080"
    command:
      - "start-dev"

volumes:
  keycloak-data-volume: